// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// run_mcmc
Rcpp::List run_mcmc(Rcpp::List args);
RcppExport SEXP _moiR_run_mcmc(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mcmc(args));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP start_profiler(SEXP);
RcppExport SEXP stop_profiler();

static const R_CallMethodDef CallEntries[] = {
    {"_moiR_run_mcmc", (DL_FUNC) &_moiR_run_mcmc, 1},
    {"start_profiler", (DL_FUNC) &start_profiler, 1},
    {"stop_profiler",  (DL_FUNC) &stop_profiler,  0},
    {NULL, NULL, 0}
};

RcppExport void R_init_moiR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
