// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ecoi_log_marginal_e_cpp
double ecoi_log_marginal_e_cpp(Rcpp::List loci_freqs, double coi_p, double coi_r, double r_alpha, double r_beta, double e, int max_coi);
RcppExport SEXP _moire_ecoi_log_marginal_e_cpp(SEXP loci_freqsSEXP, SEXP coi_pSEXP, SEXP coi_rSEXP, SEXP r_alphaSEXP, SEXP r_betaSEXP, SEXP eSEXP, SEXP max_coiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type loci_freqs(loci_freqsSEXP);
    Rcpp::traits::input_parameter< double >::type coi_p(coi_pSEXP);
    Rcpp::traits::input_parameter< double >::type coi_r(coi_rSEXP);
    Rcpp::traits::input_parameter< double >::type r_alpha(r_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type r_beta(r_betaSEXP);
    Rcpp::traits::input_parameter< double >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type max_coi(max_coiSEXP);
    rcpp_result_gen = Rcpp::wrap(ecoi_log_marginal_e_cpp(loci_freqs, coi_p, coi_r, r_alpha, r_beta, e, max_coi));
    return rcpp_result_gen;
END_RCPP
}
// ecoi_log_atom1_cpp
double ecoi_log_atom1_cpp(Rcpp::List loci_freqs, double coi_p, double coi_r, double r_alpha, double r_beta, int max_coi);
RcppExport SEXP _moire_ecoi_log_atom1_cpp(SEXP loci_freqsSEXP, SEXP coi_pSEXP, SEXP coi_rSEXP, SEXP r_alphaSEXP, SEXP r_betaSEXP, SEXP max_coiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type loci_freqs(loci_freqsSEXP);
    Rcpp::traits::input_parameter< double >::type coi_p(coi_pSEXP);
    Rcpp::traits::input_parameter< double >::type coi_r(coi_rSEXP);
    Rcpp::traits::input_parameter< double >::type r_alpha(r_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type r_beta(r_betaSEXP);
    Rcpp::traits::input_parameter< int >::type max_coi(max_coiSEXP);
    rcpp_result_gen = Rcpp::wrap(ecoi_log_atom1_cpp(loci_freqs, coi_p, coi_r, r_alpha, r_beta, max_coi));
    return rcpp_result_gen;
END_RCPP
}
// ecoi_conditional_m_cpp
Rcpp::List ecoi_conditional_m_cpp(Rcpp::List loci_freqs, double coi_p, double coi_r, double r_alpha, double r_beta, double e, int max_coi);
RcppExport SEXP _moire_ecoi_conditional_m_cpp(SEXP loci_freqsSEXP, SEXP coi_pSEXP, SEXP coi_rSEXP, SEXP r_alphaSEXP, SEXP r_betaSEXP, SEXP eSEXP, SEXP max_coiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type loci_freqs(loci_freqsSEXP);
    Rcpp::traits::input_parameter< double >::type coi_p(coi_pSEXP);
    Rcpp::traits::input_parameter< double >::type coi_r(coi_rSEXP);
    Rcpp::traits::input_parameter< double >::type r_alpha(r_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type r_beta(r_betaSEXP);
    Rcpp::traits::input_parameter< double >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type max_coi(max_coiSEXP);
    rcpp_result_gen = Rcpp::wrap(ecoi_conditional_m_cpp(loci_freqs, coi_p, coi_r, r_alpha, r_beta, e, max_coi));
    return rcpp_result_gen;
END_RCPP
}
// ecoi_log_marginal_e_from_indices_cpp
double ecoi_log_marginal_e_from_indices_cpp(Rcpp::List p_full, Rcpp::List support_idx, double coi_p, double coi_r, double r_alpha, double r_beta, double e, int max_coi);
RcppExport SEXP _moire_ecoi_log_marginal_e_from_indices_cpp(SEXP p_fullSEXP, SEXP support_idxSEXP, SEXP coi_pSEXP, SEXP coi_rSEXP, SEXP r_alphaSEXP, SEXP r_betaSEXP, SEXP eSEXP, SEXP max_coiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type p_full(p_fullSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type support_idx(support_idxSEXP);
    Rcpp::traits::input_parameter< double >::type coi_p(coi_pSEXP);
    Rcpp::traits::input_parameter< double >::type coi_r(coi_rSEXP);
    Rcpp::traits::input_parameter< double >::type r_alpha(r_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type r_beta(r_betaSEXP);
    Rcpp::traits::input_parameter< double >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type max_coi(max_coiSEXP);
    rcpp_result_gen = Rcpp::wrap(ecoi_log_marginal_e_from_indices_cpp(p_full, support_idx, coi_p, coi_r, r_alpha, r_beta, e, max_coi));
    return rcpp_result_gen;
END_RCPP
}
// ecoi_sample_log_marginal_e_cpp
double ecoi_sample_log_marginal_e_cpp(Rcpp::List pops, Rcpp::NumericVector log_pi, double coi_p, double coi_r, double r_alpha, double r_beta, double e, int max_coi);
RcppExport SEXP _moire_ecoi_sample_log_marginal_e_cpp(SEXP popsSEXP, SEXP log_piSEXP, SEXP coi_pSEXP, SEXP coi_rSEXP, SEXP r_alphaSEXP, SEXP r_betaSEXP, SEXP eSEXP, SEXP max_coiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pops(popsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type log_pi(log_piSEXP);
    Rcpp::traits::input_parameter< double >::type coi_p(coi_pSEXP);
    Rcpp::traits::input_parameter< double >::type coi_r(coi_rSEXP);
    Rcpp::traits::input_parameter< double >::type r_alpha(r_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type r_beta(r_betaSEXP);
    Rcpp::traits::input_parameter< double >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type max_coi(max_coiSEXP);
    rcpp_result_gen = Rcpp::wrap(ecoi_sample_log_marginal_e_cpp(pops, log_pi, coi_p, coi_r, r_alpha, r_beta, e, max_coi));
    return rcpp_result_gen;
END_RCPP
}
// ecoi_sample_log_atom1_cpp
double ecoi_sample_log_atom1_cpp(Rcpp::List pops, Rcpp::NumericVector log_pi, double coi_p, double coi_r, double r_alpha, double r_beta, int max_coi);
RcppExport SEXP _moire_ecoi_sample_log_atom1_cpp(SEXP popsSEXP, SEXP log_piSEXP, SEXP coi_pSEXP, SEXP coi_rSEXP, SEXP r_alphaSEXP, SEXP r_betaSEXP, SEXP max_coiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pops(popsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type log_pi(log_piSEXP);
    Rcpp::traits::input_parameter< double >::type coi_p(coi_pSEXP);
    Rcpp::traits::input_parameter< double >::type coi_r(coi_rSEXP);
    Rcpp::traits::input_parameter< double >::type r_alpha(r_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type r_beta(r_betaSEXP);
    Rcpp::traits::input_parameter< int >::type max_coi(max_coiSEXP);
    rcpp_result_gen = Rcpp::wrap(ecoi_sample_log_atom1_cpp(pops, log_pi, coi_p, coi_r, r_alpha, r_beta, max_coi));
    return rcpp_result_gen;
END_RCPP
}
// run_mcmc
Rcpp::List run_mcmc(Rcpp::List args);
RcppExport SEXP _moire_run_mcmc(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mcmc(args));
    return rcpp_result_gen;
END_RCPP
}
// tbb_enabled
SEXP tbb_enabled();
RcppExport SEXP _moire_tbb_enabled() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(tbb_enabled());
    return rcpp_result_gen;
END_RCPP
}
// compare_mobius_inclusion_exclusion
Rcpp::List compare_mobius_inclusion_exclusion(Rcpp::NumericVector p_full, Rcpp::IntegerVector support_vec, int max_n);
RcppExport SEXP _moire_compare_mobius_inclusion_exclusion(SEXP p_fullSEXP, SEXP support_vecSEXP, SEXP max_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_full(p_fullSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type support_vec(support_vecSEXP);
    Rcpp::traits::input_parameter< int >::type max_n(max_nSEXP);
    rcpp_result_gen = Rcpp::wrap(compare_mobius_inclusion_exclusion(p_full, support_vec, max_n));
    return rcpp_result_gen;
END_RCPP
}
// moire_profiler_stats
Rcpp::DataFrame moire_profiler_stats();
RcppExport SEXP _moire_moire_profiler_stats() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(moire_profiler_stats());
    return rcpp_result_gen;
END_RCPP
}
// moire_profiler_reset
void moire_profiler_reset();
RcppExport SEXP _moire_moire_profiler_reset() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    moire_profiler_reset();
    return R_NilValue;
END_RCPP
}
// moire_pam_cache_stats
Rcpp::List moire_pam_cache_stats();
RcppExport SEXP _moire_moire_pam_cache_stats() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(moire_pam_cache_stats());
    return rcpp_result_gen;
END_RCPP
}
// moire_pam_cache_reset
void moire_pam_cache_reset();
RcppExport SEXP _moire_moire_pam_cache_reset() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    moire_pam_cache_reset();
    return R_NilValue;
END_RCPP
}
// start_profiler
SEXP start_profiler(SEXP str);
RcppExport SEXP _moire_start_profiler(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(start_profiler(str));
    return rcpp_result_gen;
END_RCPP
}
// stop_profiler
SEXP stop_profiler();
RcppExport SEXP _moire_stop_profiler() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(stop_profiler());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_moire_ecoi_log_marginal_e_cpp", (DL_FUNC) &_moire_ecoi_log_marginal_e_cpp, 7},
    {"_moire_ecoi_log_atom1_cpp", (DL_FUNC) &_moire_ecoi_log_atom1_cpp, 6},
    {"_moire_ecoi_conditional_m_cpp", (DL_FUNC) &_moire_ecoi_conditional_m_cpp, 7},
    {"_moire_ecoi_log_marginal_e_from_indices_cpp", (DL_FUNC) &_moire_ecoi_log_marginal_e_from_indices_cpp, 8},
    {"_moire_ecoi_sample_log_marginal_e_cpp", (DL_FUNC) &_moire_ecoi_sample_log_marginal_e_cpp, 8},
    {"_moire_ecoi_sample_log_atom1_cpp", (DL_FUNC) &_moire_ecoi_sample_log_atom1_cpp, 7},
    {"_moire_run_mcmc", (DL_FUNC) &_moire_run_mcmc, 1},
    {"_moire_tbb_enabled", (DL_FUNC) &_moire_tbb_enabled, 0},
    {"_moire_compare_mobius_inclusion_exclusion", (DL_FUNC) &_moire_compare_mobius_inclusion_exclusion, 3},
    {"_moire_moire_profiler_stats", (DL_FUNC) &_moire_moire_profiler_stats, 0},
    {"_moire_moire_profiler_reset", (DL_FUNC) &_moire_moire_profiler_reset, 0},
    {"_moire_moire_pam_cache_stats", (DL_FUNC) &_moire_moire_pam_cache_stats, 0},
    {"_moire_moire_pam_cache_reset", (DL_FUNC) &_moire_moire_pam_cache_reset, 0},
    {"_moire_start_profiler", (DL_FUNC) &_moire_start_profiler, 1},
    {"_moire_stop_profiler", (DL_FUNC) &_moire_stop_profiler, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_moire(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
