#' Sample from the target distribution using MCMC
#'
#' @export
#'
#' @param data Data to be used in MCMC, as generated by the `load_*_data` functions
#' @param is_missing Boolean matrix indicating whether the observation
#'  should be treated as missing data and ignored. Number of rows equals the
#'  number of loci, number of columns equals the number samples. Alternatively,
#'  the user may pass in FALSE if no data should be considered missing.
#' @param allow_relatedness Bool indicating whether or not to allow relatedness
#'  within host
#' @param thin Positive Integer. How often to sample from mcmc,
#'  1 means do not thin
#' @param burnin Positive Integer. Number of MCMC samples to
#'  discard as burnin
#' @param samples_per_chain Positive Integer. Number of samples to take
#'  after burnin
#' @param verbose Logical indicating if progress is printed
#' @param use_message Logical indicating if progress is printed using message or print
#' @param eps_pos_alpha Positive Numeric. Alpha parameter in
#'  Beta distribution for eps_pos prior
#' @param eps_pos_beta Positive Numeric. Beta parameter in
#'  Beta distribution for eps_pos prior
#' @param eps_neg_alpha Positive Numeric. Alpha parameter in
#'  Beta distribution for eps_neg prior
#' @param eps_neg_beta Positive Numeric. Beta parameter in
#'  Beta distribution for eps_neg prior
#' @param r_alpha Positive Numeric. Alpha parameter in Beta
#' distribution for relatedness prior
#' @param r_beta Positive Numeric. Beta parameter in Beta
#' distribution for relatedness prior
#' @param mean_coi_shape shape parameter for gamma hyperprior on mean COI
#' @param mean_coi_scale scale parameter for gamma hyperprior on mean COI
#' @param max_eps_pos Numeric. Maximum allowed value for eps_pos
#' @param max_eps_neg Numeric. Maximum allowed value for eps_neg
#' @param max_coi Positive Numeric. Maximum allowed complexity of infection
#' @param record_latent_genotypes Logical indicating whether or not to record
#' the latent genotypes at each step of the MCMC. WARNING: This will increase
#' the size of the output object significantly.
#' @param num_chains Total number of chains to run, possibly simultaneously
#' @param num_cores How many independent chains to run at once, passed to
#'  [parallel::mclapply()] as `mc.cores`. `num_cores * pt_num_threads` should
#'  not exceed the number of cores available on your system.
#' @param pt_chains Total number of chains to run with parallel tempering or a
#' vector containing the temperatures that should be used for parallel tempering.
#' @param pt_grad Power to raise parallel tempering chains to. A value of 1
#'  results in evenly distributed temperatures between \[0,1\], below 1 will bias
#'  towards 1 and above 1 will bias towards 0. Only used if pt_chains is a
#'  single value (i.e. not a vector).
#' @param pt_num_threads Total number of OMP parallel threads to be used to
#'  process parallel tempered chains
#'  num_cores * pt_num_threads should not exceed the number of cores available
#'  on your system.
#' @param adapt_temp Logical indicating whether or not to adapt the parallel
#' tempering temperatures. If TRUE, the temperatures will be adapted during the
#' `burnin` period, starting after `pre_adapt_steps` steps. The adaptation will
#' occur every `temp_adapt_steps` steps until burnin is complete. The range of
#' temperatures will remain the same as specified by `pt_chains`.
#' @param pre_adapt_steps Number of steps to take before starting to adapt the
#' parallel tempering temperatures. Only used if `adapt_temp` is TRUE.
#' @param temp_adapt_steps Number of steps to take between temperature
#' adaptation steps. Only used if `adapt_temp` is TRUE.
#' @param max_initialization_tries Number of times to try to initialize the
#' chain before giving up
#' @param seed Integer seed. `NULL` draws from the current R RNG a value that
#'  still fits after per-chain offsets. The value used is returned as `$seed`
#'  and printed if the run errors; per-chain offsets are `$chain_seeds`.
#'  Replay needs the same sampler settings; `num_cores` does not affect the
#'  draws.
#' @param max_runtime Maximum runtime in minutes. If the MCMC is running for
#' more than this amount of time, the function will stop and return the current
#' state of the MCMC.
#'
#' @section Initialization failure:
#' If every Initialization retry yields a non-finite genotyping log-likelihood,
#' `run_mcmc` stops with a classed error
#' (`moire_initialization_failure`) whose message includes rule-based guidance
#' and whose `$diagnostics` field has Failure-locus counts and classification
#' (Consistent failure cause vs Hard starting set). Inspect with
#' `tryCatch(run_mcmc(...), error = function(e) e$diagnostics)`.
run_mcmc <-
  function(data,
           is_missing = FALSE,
           allow_relatedness = TRUE,
           thin = 1,
           burnin = 1e4,
           samples_per_chain = 1e3,
           verbose = TRUE,
           use_message = FALSE,
           eps_pos_alpha = 1,
           eps_pos_beta = 1,
           eps_neg_alpha = 1,
           eps_neg_beta = 1,
           r_alpha = 1,
           r_beta = 1,
           mean_coi_shape = .1,
           mean_coi_scale = 10,
           max_eps_pos = 2,
           max_eps_neg = 2,
           max_coi = 40,
           record_latent_genotypes = FALSE,
           num_chains = 1,
           num_cores = 1,
           pt_chains = 1,
           pt_grad = 1,
           pt_num_threads = 1,
           adapt_temp = TRUE,
           pre_adapt_steps = 25,
           temp_adapt_steps = 25,
           max_initialization_tries = 10000,
           max_runtime = Inf,
           seed = NULL) {
    start_time <- Sys.time()
    seeds <- resolve_mcmc_seeds(seed, num_chains)
    seed <- seeds$seed
    chain_seeds <- seeds$chain_seeds

    run_completed <- FALSE
    on.exit({
      if (!run_completed) {
        message(sprintf(
          "moire::run_mcmc() did not complete. Re-run with seed = %d to reproduce.",
          seed
        ))
      }
    }, add = TRUE)
    args <- mget(names(formals()), envir = environment(), inherits = FALSE)
    mcmc_args <- args
    mcmc_args$data <- data$data
    mcmc_args$sample_ids <- data$sample_ids
    mcmc_args$loci <- data$loci

    ## if is_missing == FALSE, then generate a default FALSE matrix
    suppressWarnings({
      if (inherits(mcmc_args$is_missing, "logical") && mcmc_args$is_missing == FALSE) {
        num_loci <- length(mcmc_args$loci)
        num_biological_samples <- length(mcmc_args$sample_ids)
        mcmc_args$is_missing <- matrix(
          FALSE,
          nrow = num_loci,
          ncol = num_biological_samples
        )
      }
    })

    total_alleles <- lapply(mcmc_args$data, function(x) {
      return(length(x[[1]]))
    })

    if (any(total_alleles < 2)) {
      stop("Loci with less than 2 alleles present, remove these loci")
    }

    if (max_coi < 1) {
      stop("Max COI must be greater than 1")
    }

    if (length(pt_chains) == 1) {
      mcmc_args$pt_chains <- seq(1, 0, length.out = pt_chains)**pt_grad
    }


    res <- list()
    chains <- list()
    handle_chain_result <- function(chain) {
      if (isTRUE(chain$initialization_failed)) {
        stop_initialization_failure(
          chain$diagnostics,
          sample_ids = mcmc_args$sample_ids,
          loci = mcmc_args$loci
        )
      }
      chain$mean_coi <- chain$lam_coi / (1 - exp(-chain$lam_coi))
      chain
    }
    if (num_chains > 1) {
      chains <- parallel::mclapply(
        1:num_chains,
        function(i) {
          mcmc_args$chain_number <- i
          mcmc_args$seed <- chain_seeds[[i]]
          mcmc_args$simple_verbose <- (mcmc_args$num_chains > 1)
          mcmc_args$samples <- round(mcmc_args$samples_per_chain)
          handle_chain_result(run_mcmc_rcpp(mcmc_args))
        },
        mc.cores = num_cores
      )
    } else {
      mcmc_args$chain_number <- 1
      mcmc_args$simple_verbose <- FALSE
      mcmc_args$samples <- mcmc_args$samples_per_chain
      chains[[1]] <- handle_chain_result(run_mcmc_rcpp(mcmc_args))
    }

    end_time <- Sys.time()

    res$runtime <- end_time - start_time
    res$chains <- chains
    res$args <- args
    res$seed <- seed
    res$chain_seeds <- chain_seeds

    run_completed <- TRUE
    res
  }

# Must stay in sync with Seed::independent_chain_stride in src/seed.h.
# PT replicas use parent+0, parent+1, ... so independent MCMCs are spaced
# this far apart.
resolve_mcmc_seeds <- function(seed, num_chains) {
  seed_stride <- 1000L
  max_seed <- .Machine$integer.max - seed_stride * max(num_chains - 1L, 0L)
  if (max_seed < 1L) {
    stop("`num_chains` is too large to form integer chain seeds")
  }
  if (is.null(seed)) {
    seed <- sample.int(max_seed, 1L)
  }
  seed <- as.integer(seed)
  if (length(seed) != 1L || is.na(seed)) {
    stop("`seed` must be a single integer")
  }
  if (seed > max_seed) {
    stop(
      "`seed` is too large for num_chains = ", num_chains,
      "; maximum is ", max_seed
    )
  }
  list(
    seed = seed,
    chain_seeds = seed + (seq_len(num_chains) - 1L) * seed_stride
  )
}
