#' Sample from the target distribution using MCMC
#'
#' @export
#'
#' @param data Data to be used in MCMC, as generated by the `load_*_data` functions
#' @param is_missing Boolean matrix indicating whether the observation
#'  should be treated as missing data and ignored. Number of rows equals the
#'  number of loci, number of columns equals the number samples. Alternatively,
#'  the user may pass in FALSE if no data should be considered missing.
#' @param allow_relatedness Bool indicating whether or not to allow relatedness
#'  within host
#' @param thin Positive Integer. How often to sample from mcmc,
#'  1 means do not thin
#' @param burnin Positive Integer. Number of MCMC samples to
#'  discard as burnin
#' @param samples_per_chain Positive Integer. Number of samples to take
#'  after burnin
#' @param verbose Logical indicating if progress is printed
#' @param use_message Logical indicating if progress is printed using message or print
#' @param eps_pos_alpha Positive Numeric. Alpha parameter in
#'  Beta distribution for eps_pos prior
#' @param eps_pos_beta Positive Numeric. Beta parameter in
#'  Beta distribution for eps_pos prior
#' @param eps_neg_alpha Positive Numeric. Alpha parameter in
#'  Beta distribution for eps_neg prior
#' @param eps_neg_beta Positive Numeric. Beta parameter in
#'  Beta distribution for eps_neg prior
#' @param r_alpha Positive Numeric. Alpha parameter in Beta
#' distribution for relatedness prior
#' @param r_beta Positive Numeric. Beta parameter in Beta
#' distribution for relatedness prior
#' @param population_coi_p_alpha Alpha for Beta prior on negative-binomial p (COI)
#' @param population_coi_p_beta Beta for Beta prior on negative-binomial p (COI)
#' @param population_coi_r_shape Shape for gamma prior on negative-binomial r (COI)
#' @param population_coi_r_rate Rate for gamma prior on negative-binomial r (COI)
#' @param population_coi_lam_shape Shape for gamma prior on Poisson rate (COI)
#' @param population_coi_lam_rate Rate for gamma prior on Poisson rate (COI)
#' @param num_populations Number of populations
#' @param populations_prior Prior probability for each population (length \code{num_populations} or 1)
#' @param max_eps_pos Numeric. Maximum allowed value for eps_pos
#' @param max_eps_neg Numeric. Maximum allowed value for eps_neg
#' @param max_coi Positive Numeric. Maximum allowed complexity of infection
#' @param population_coi_method Character. Method for modeling population COI.
#'  For negative binomial model, accepts: "nb", "nbinom", "negbinom", "negative_binomial".
#'  For Poisson model, accepts: "pois", "poisson".
#' @param record_latent_genotypes Logical indicating whether or not to record
#' the latent genotypes at each step of the MCMC. WARNING: This will increase
#' the size of the output object significantly.
#' @param num_chains Total number of chains to run, possibly simultaneously
#' @param num_cores Total OMP parallel threads to use to run chains.
#'  num_cores * pt_num_threads should not exceed the number of cores available
#'  on your system.
#' @param pt_chains Total number of chains to run with parallel tempering or a
#' vector containing the temperatures that should be used for parallel tempering.
#' @param pt_grad Power to raise parallel tempering chains to. A value of 1
#'  results in evenly distributed temperatures between \[0,1\], below 1 will bias
#'  towards 1 and above 1 will bias towards 0. Only used if pt_chains is a
#'  single value (i.e. not a vector).
#' @param pt_num_threads Total number of OMP parallel threads to be used to
#'  process parallel tempered chains
#'  num_cores * pt_num_threads should not exceed the number of cores available
#'  on your system.
#' @param adapt_temp Logical indicating whether or not to adapt the parallel
#' tempering temperatures. If TRUE, the temperatures will be adapted during the
#' `burnin` period, starting after `pre_adapt_steps` steps. The adaptation will
#' occur every `temp_adapt_steps` steps until burnin is complete. The range of
#' temperatures will remain the same as specified by `pt_chains`.
#' @param pre_adapt_steps Number of steps to take before starting to adapt the
#' parallel tempering temperatures. Only used if `adapt_temp` is TRUE.
#' @param temp_adapt_steps Number of steps to take between temperature
#' adaptation steps. Only used if `adapt_temp` is TRUE.
#' @param max_initialization_tries Number of times to try to initialize the
#' chain before giving up
#' @param max_runtime Maximum runtime in minutes. If the MCMC is running for
#' more than this amount of time, the function will stop and return the current
#' state of the MCMC.
#' @param initial_allele_frequencies Optional list of initial allele frequencies
#' for each population. If provided, should be a list of length `num_populations`,
#' where each element is a list of length `num_loci`, and each locus element is
#' a numeric vector of allele frequencies that sum to 1. If NULL, allele frequencies
#' will be initialized using clustering-based approach.
run_mcmc <-
  function(data,
           is_missing = FALSE,
           allow_relatedness = TRUE,
           thin = 1,
           burnin = 1e4,
           samples_per_chain = 1e3,
           verbose = TRUE,
           use_message = FALSE,
           eps_pos_alpha = 1,
           eps_pos_beta = 1,
           eps_neg_alpha = 1,
           eps_neg_beta = 1,
           r_alpha = 1,
           r_beta = 1,
           population_coi_p_alpha = 1,
           population_coi_p_beta = 1,
           population_coi_r_shape = .1,
           population_coi_r_rate = 10,
           population_coi_lam_shape = .1,
           population_coi_lam_rate = 10,
           population_coi_method = "nb",
           num_populations = 1,
           populations_prior = NULL,
           max_eps_pos = 2,
           max_eps_neg = 2,
           max_coi = 40,
           record_latent_genotypes = FALSE,
           num_chains = 1,
           num_cores = 1,
           pt_chains = 1,
           pt_grad = 1,
           pt_num_threads = 1,
           adapt_temp = TRUE,
           pre_adapt_steps = 25,
           temp_adapt_steps = 25,
           max_initialization_tries = 10000,
           max_runtime = Inf,
           initial_allele_frequencies = NULL) {
    start_time <- Sys.time()
    args <- as.list(environment())
    mcmc_args <- as.list(environment())
    mcmc_args$data <- data$data
    mcmc_args$sample_ids <- data$sample_ids
    mcmc_args$loci <- data$loci

    ## if is_missing == FALSE, then generate a default FALSE matrix
    suppressWarnings({
      if (inherits(mcmc_args$is_missing, "logical") && mcmc_args$is_missing == FALSE) {
        num_loci <- length(mcmc_args$loci)
        num_biological_samples <- length(mcmc_args$sample_ids)
        mcmc_args$is_missing <- matrix(
          FALSE,
          nrow = num_loci,
          ncol = num_biological_samples
        )
      }
    })

    if (is.null(mcmc_args$populations_prior)) {
      mcmc_args$populations_prior <- rep(1 / num_populations, num_populations)
    }

    if (length(mcmc_args$populations_prior) == 1) {
      mcmc_args$populations_prior <- rep(mcmc_args$populations_prior, num_populations)
    }

    if (length(mcmc_args$populations_prior) != num_populations) {
      stop("populations_prior must be a scalar or a vector of length num_populations.")
    }
    
    # Log information about initial allele frequencies
    if (!is.null(mcmc_args$initial_allele_frequencies)) {
      cat_progress_header("MCMC Initialization with Custom Allele Frequencies", data)
      cat("Using provided initial allele frequencies\n")
      cat("Number of populations:", length(mcmc_args$initial_allele_frequencies), "\n")
      for (i in seq_along(mcmc_args$initial_allele_frequencies)) {
        cat("Population", i, "has", length(mcmc_args$initial_allele_frequencies[[i]]), "loci\n")
      }
      cat("========================================================\n")
    } else {
      cat_progress_header("MCMC Initialization with Clustering-Based Approach", data)
      cat("No initial allele frequencies provided, using clustering-based initialization\n")
      cat("============================================================\n")
    }

    total_alleles <- lapply(mcmc_args$data, function(x) {
      return(length(x[[1]]))
    })

    if (any(total_alleles < 2)) {
      stop("Loci with less than 2 alleles present, remove these loci.")
    }

    if (max_coi < 1) {
      stop("max_coi must be greater than 1.")
    }

    if (length(pt_chains) == 1) {
      mcmc_args$pt_chains <- seq(1, 0, length.out = pt_chains)**pt_grad
    }

    # Normalize population_coi_method to standard values
    nb_aliases <- c("nb", "nbinom", "negbinom", "negative_binomial")
    poisson_aliases <- c("pois", "poisson")

    if (mcmc_args$population_coi_method %in% nb_aliases) {
      mcmc_args$population_coi_method <- "nb"
    } else if (mcmc_args$population_coi_method %in% poisson_aliases) {
      mcmc_args$population_coi_method <- "poisson"
    } else {
      stop(
        "population_coi_method must be one of: ",
        paste(c(nb_aliases, poisson_aliases), collapse = ", ")
      )
    }

    res <- list()
    chains <- list()
    if (num_chains > 1) {
      chains <- parallel::mclapply(
        1:num_chains,
        function(i) {
          mcmc_args$chain_number <- i
          mcmc_args$simple_verbose <- (mcmc_args$num_chains > 1)
          mcmc_args$samples <- round(mcmc_args$samples_per_chain)
          chain <- run_mcmc_rcpp(mcmc_args)
          if (mcmc_args$population_coi_method == "poisson") {
            chain$mean_coi <- chain$lam_coi / (1 - exp(-chain$population_lam_coi))
          }
          return(chain)
        },
        mc.cores = num_cores
      )
    } else {
      mcmc_args$chain_number <- 1
      mcmc_args$simple_verbose <- FALSE
      mcmc_args$samples <- mcmc_args$samples_per_chain
      chain <- run_mcmc_rcpp(mcmc_args)
      if (mcmc_args$population_coi_method == "poisson") {
        chain$mean_coi <- chain$lam_coi / (1 - exp(-chain$population_lam_coi))
      }
      chains[[1]] <- chain
    }

    end_time <- Sys.time()

    res$runtime <- end_time - start_time
    res$chains <- chains
    res$args <- args

    res
  }
