# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_mcmc_rcpp <- function(args) {
    .Call(`_moire_run_mcmc`, args)
}

openmp_enabled <- function() {
    .Call(`_moire_openmp_enabled`)
}

start_profiler <- function(str) {
    .Call(`_moire_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_moire_stop_profiler`)
}

