# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_mcmc_rcpp <- function(args) {
    .Call(`_moire_run_mcmc`, args)
}

tbb_enabled <- function() {
    .Call(`_moire_tbb_enabled`)
}

compare_mobius_inclusion_exclusion <- function(p_full, support_vec, max_n) {
    .Call(`_moire_compare_mobius_inclusion_exclusion`, p_full, support_vec, max_n)
}

moire_profiler_stats <- function() {
    .Call(`_moire_moire_profiler_stats`)
}

moire_profiler_reset <- function() {
    invisible(.Call(`_moire_moire_profiler_reset`))
}

start_profiler <- function(str) {
    .Call(`_moire_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_moire_stop_profiler`)
}

