# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ecoi_log_marginal_e_cpp <- function(loci_freqs, coi_p, coi_r, r_alpha, r_beta, e, max_coi) {
    .Call(`_moire_ecoi_log_marginal_e_cpp`, loci_freqs, coi_p, coi_r, r_alpha, r_beta, e, max_coi)
}

ecoi_log_atom1_cpp <- function(loci_freqs, coi_p, coi_r, r_alpha, r_beta, max_coi) {
    .Call(`_moire_ecoi_log_atom1_cpp`, loci_freqs, coi_p, coi_r, r_alpha, r_beta, max_coi)
}

ecoi_conditional_m_cpp <- function(loci_freqs, coi_p, coi_r, r_alpha, r_beta, e, max_coi) {
    .Call(`_moire_ecoi_conditional_m_cpp`, loci_freqs, coi_p, coi_r, r_alpha, r_beta, e, max_coi)
}

ecoi_log_marginal_e_from_indices_cpp <- function(p_full, support_idx, coi_p, coi_r, r_alpha, r_beta, e, max_coi) {
    .Call(`_moire_ecoi_log_marginal_e_from_indices_cpp`, p_full, support_idx, coi_p, coi_r, r_alpha, r_beta, e, max_coi)
}

ecoi_sample_log_marginal_e_cpp <- function(pops, log_pi, coi_p, coi_r, r_alpha, r_beta, e, max_coi) {
    .Call(`_moire_ecoi_sample_log_marginal_e_cpp`, pops, log_pi, coi_p, coi_r, r_alpha, r_beta, e, max_coi)
}

ecoi_sample_log_atom1_cpp <- function(pops, log_pi, coi_p, coi_r, r_alpha, r_beta, max_coi) {
    .Call(`_moire_ecoi_sample_log_atom1_cpp`, pops, log_pi, coi_p, coi_r, r_alpha, r_beta, max_coi)
}

run_mcmc_rcpp <- function(args) {
    .Call(`_moire_run_mcmc`, args)
}

tbb_enabled <- function() {
    .Call(`_moire_tbb_enabled`)
}

compare_mobius_inclusion_exclusion <- function(p_full, support_vec, max_n) {
    .Call(`_moire_compare_mobius_inclusion_exclusion`, p_full, support_vec, max_n)
}

moire_profiler_stats <- function() {
    .Call(`_moire_moire_profiler_stats`)
}

moire_profiler_reset <- function() {
    invisible(.Call(`_moire_moire_profiler_reset`))
}

moire_pam_cache_stats <- function() {
    .Call(`_moire_moire_pam_cache_stats`)
}

moire_pam_cache_reset <- function() {
    invisible(.Call(`_moire_moire_pam_cache_reset`))
}

start_profiler <- function(str) {
    .Call(`_moire_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_moire_stop_profiler`)
}

